2024-08-28 19:05:26.275 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-08-28 19:05:26.279 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-08-28 19:05:26.979 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2024-08-28 19:05:30.091 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-08-28 19:05:32.485 ERROR (MainThread) [homeassistant.components.mqtt.client] Failed to connect to MQTT server due to exception: [Errno 111] Connection refused
2024-08-28 19:05:49.599 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
2024-08-28 19:23:06.891 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching HVAC-HV2 (HY02/HY03 at 192.168.1.90) data: [Errno -4008] Received data packet check error: Expected a checksum of 255 and received 41852
2024-08-28 19:24:50.316 WARNING (MainThread) [zigpy.application] Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x04E9)
2024-08-28 19:24:50.348 WARNING (MainThread) [zigpy.application] Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x04E9)
2024-08-28 19:24:50.358 WARNING (MainThread) [zigpy.application] Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x04E9)
2024-08-28 19:24:50.371 WARNING (MainThread) [zigpy.application] Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x04E9)
2024-08-28 19:24:50.399 WARNING (MainThread) [zigpy.application] Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x04E9)
2024-08-28 19:24:50.423 WARNING (MainThread) [zigpy.application] Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x04E9)
2024-08-28 19:24:50.447 WARNING (MainThread) [zigpy.application] Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x04E9)
2024-08-28 19:24:50.469 WARNING (MainThread) [zigpy.application] Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x04E9)
2024-08-28 19:24:50.480 WARNING (MainThread) [zigpy.application] Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x04E9)
2024-08-28 19:24:50.504 WARNING (MainThread) [zigpy.application] Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x04E9)
2024-08-28 19:31:16.828 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching HVAC-HV2 (HY02/HY03 at 192.168.1.90) data: [Errno -4000] Network timeout: No response received within 10s
2024-08-28 19:38:40.828 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching HVAC-HV2 (HY02/HY03 at 192.168.1.90) data: [Errno -4000] Network timeout: No response received within 10s
2024-08-28 19:41:55.828 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching HVAC-HV2 (HY02/HY03 at 192.168.1.90) data: [Errno -4000] Network timeout: No response received within 10s
2024-08-28 19:44:05.828 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching HVAC-HV2 (HY02/HY03 at 192.168.1.90) data: [Errno -4000] Network timeout: No response received within 10s
2024-08-28 19:44:23.939 WARNING (MainThread) [zigpy.application] Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x04E9)
2024-08-28 19:44:23.968 WARNING (MainThread) [zigpy.application] Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x04E9)
2024-08-28 19:44:23.983 WARNING (MainThread) [zigpy.application] Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x04E9)
2024-08-28 19:44:23.993 WARNING (MainThread) [zigpy.application] Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x04E9)
2024-08-28 19:44:24.019 WARNING (MainThread) [zigpy.application] Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x04E9)
2024-08-28 19:44:24.034 WARNING (MainThread) [zigpy.application] Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x04E9)
2024-08-28 19:44:24.069 WARNING (MainThread) [zigpy.application] Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x04E9)
2024-08-28 19:44:24.089 WARNING (MainThread) [zigpy.application] Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x04E9)
2024-08-28 19:44:24.110 WARNING (MainThread) [zigpy.application] Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x04E9)
2024-08-28 19:44:24.118 WARNING (MainThread) [zigpy.application] Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x04E9)
2024-08-28 19:46:25.829 WARNING (MainThread) [homeassistant.components.broadlink.updater] Disconnected from HVAC-HV2 (HY02/HY03 at 192.168.1.90)
2024-08-28 19:53:16.031 WARNING (MainThread) [homeassistant.components.broadlink.updater] Connected to HVAC-HV2 (HY02/HY03 at 192.168.1.90)
2024-08-28 19:54:25.828 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching HVAC-HV2 (HY02/HY03 at 192.168.1.90) data: [Errno -4000] Network timeout: No response received within 10s
2024-08-28 19:56:35.828 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching HVAC-HV2 (HY02/HY03 at 192.168.1.90) data: [Errno -4000] Network timeout: No response received within 10s
2024-08-28 19:58:55.828 WARNING (MainThread) [homeassistant.components.broadlink.updater] Disconnected from HVAC-HV2 (HY02/HY03 at 192.168.1.90)
